### ISSUE TITLE
'Namespace' object has no attribute 'extended_default_ignore'

### ISSUE THREAD

**Issue by frafra** [flakehell/flakehell#10]
It looks like there is a problem while executing flake.

```
pdm run flake8helled viltkamera_manager.py 
Traceback (most recent call last):
  File "/home/frafra/Code/viltkamera-manager/__pypackages__/3.8/bin/flake8helled", line 8, in <module>
    sys.exit(flake8_entrypoint())
  File "/home/frafra/Code/viltkamera-manager/__pypackages__/3.8/lib/flakehell/_cli.py", line 51, in flake8_entrypoint
    exit_code, msg = main(['lint'] + argv)
  File "/home/frafra/Code/viltkamera-manager/__pypackages__/3.8/lib/flakehell/_cli.py", line 32, in main
    return COMMANDS[command_name](argv=argv[1:])
  File "/home/frafra/Code/viltkamera-manager/__pypackages__/3.8/lib/flakehell/commands/_lint.py", line 12, in lint_command
    app.run(argv)
  File "/home/frafra/Code/viltkamera-manager/__pypackages__/3.8/lib/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/home/frafra/Code/viltkamera-manager/__pypackages__/3.8/lib/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "/home/frafra/Code/viltkamera-manager/__pypackages__/3.8/lib/flake8/main/application.py", line 337, in initialize
    self.make_guide()
  File "/home/frafra/Code/viltkamera-manager/__pypackages__/3.8/lib/flakehell/_patched/_app.py", line 177, in make_guide
    self.guide = FlakeHellStyleGuideManager(self.options, self.formatter)
  File "/home/frafra/Code/viltkamera-manager/__pypackages__/3.8/lib/flakehell/_patched/_style_guide.py", line 17, in __init__
    super().__init__(options, formatter, decider)
  File "/home/frafra/Code/viltkamera-manager/__pypackages__/3.8/lib/flake8/style_guide.py", line 339, in __init__
    self.decider = decider or DecisionEngine(options)
  File "/home/frafra/Code/viltkamera-manager/__pypackages__/3.8/lib/flake8/style_guide.py", line 171, in __init__
    ).union(options.extended_default_ignore)
AttributeError: 'Namespace' object has no attribute 'extended_default_ignore'
```

**Comment by espdev** [comment]
The same issue with `flake8 == 3.9.1`. With `flake8 3.9.0` it works without the error.

**Comment by fliiiix** [comment]
Looks like flakehell is using unsupported private interfaces see https://github.com/PyCQA/flake8/issues/1318

**Comment by nobbynobbs** [comment]
@mario-bermonti could you explain please? I've cloned your `stimpool` project, install it with poetry, then update `flake` to 3.9.1 (in poetry.lock pinned 3.9.0) and run flakehell. And looks like it works.

**Comment by mario-bermonti** [comment]
@nobbynobbs I made a mistake. It's working fine. I must have gotten confused with the original time the Github action ran and it failed. 

Thanks!

**Comment by aaronsteers** [comment]
Has anyone tested with flake `3.9.2` or does this still require either reverting to `3.9.0` or using @nobbynobbs' workaround [above](https://github.com/flakehell/flakehell/issues/10#issuecomment-822720074)?

https://flake8.pycqa.org/en/latest/release-notes/3.9.2.html#bugs-fixed
