### ISSUE TITLE
Flakehell fails with flake8==4.0.0

### ISSUE THREAD

**Issue by KPLauritzen** [flakehell/flakehell#18]
When installing flakehell in a clean virtualenv it automatically installs the newly released flake8==4.0.0.
But when running flakehell, it fails immediately:

```shell
pip install flakehell flake8==4.0.0
flakehell
```
returns
```text
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\<user>\<project>\venv\Scripts\flakehell.exe\__main__.py", line 4, in <module>
  File "c:\users\<user>\<project>\venv\lib\site-packages\flakehell\__init__.py", line 5, in <module>
    from ._cli import entrypoint, flake8_entrypoint
  File "c:\users\<user>\<project>\venv\lib\site-packages\flakehell\_cli.py", line 9, in <module>
    from .commands import COMMANDS
  File "c:\users\<user>\<project>\venv\lib\site-packages\flakehell\commands\__init__.py", line 5, in <module>
    from ._baseline import baseline_command
  File "c:\users\<user>\<project>\venv\lib\site-packages\flakehell\commands\_baseline.py", line 6, in <module>
    from .._patched import FlakeHellApplication
  File "c:\users\<user>\<project>\venv\lib\site-packages\flakehell\_patched\__init__.py", line 2, in <module>
    from ._app import FlakeHellApplication
  File "c:\users\<user>\<project>\venv\lib\site-packages\flakehell\_patched\_app.py", line 10, in <module>
    from flake8.options.config import MergedConfigParser, get_local_plugins
ImportError: cannot import name 'MergedConfigParser' from 'flake8.options.config' (c:\users\<user>\<project>\venv\lib\site-packages\flake8\options\config.py)
```

It can be fixed by specifying flake8==3.9.0, but that is not a very satisfying solution.

**Comment by bitphage** [comment]
```diff
diff --git a/pyproject.toml b/pyproject.toml
index 05c6f83..ccb3bbc 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -67,7 +67,7 @@ requires-python=">=3.5"
 requires=[
     "colorama",
     "entrypoints",
-    "flake8>=3.8.0",
+    "flake8>=3.8.0,<3.9.0",
     "pygments",
     "toml",
     "urllib3",
```

**Comment by jose-rojas0** [comment]
For those looking for an alternative - take a look at https://github.com/flakeheaven/flakeheaven
