### ISSUE TITLE
ImportError: cannot import name 'MergedConfigParser' from 'flake8.options.config' 

### ISSUE THREAD

**Issue by BenCretois** [flakehell/flakehell#22]
I cannot use flakehell 0.8.0 or 0.9.0. I am using Python 3.10 in a Poetry venv.

```
$ flake8helled --help
Traceback (most recent call last):
  File "/home/NINA.NO/benjamin.cretois/.cache/pypoetry/virtualenvs/edna-etl-HihhyK_G-py3.10/bin/flake8helled", line 5, in <module>
    from flakehell import flake8_entrypoint
  File "/home/NINA.NO/benjamin.cretois/.cache/pypoetry/virtualenvs/edna-etl-HihhyK_G-py3.10/lib/python3.10/site-packages/flakehell/__init__.py", line 5, in <module>
    from ._cli import entrypoint, flake8_entrypoint
  File "/home/NINA.NO/benjamin.cretois/.cache/pypoetry/virtualenvs/edna-etl-HihhyK_G-py3.10/lib/python3.10/site-packages/flakehell/_cli.py", line 9, in <module>
    from .commands import COMMANDS
  File "/home/NINA.NO/benjamin.cretois/.cache/pypoetry/virtualenvs/edna-etl-HihhyK_G-py3.10/lib/python3.10/site-packages/flakehell/commands/__init__.py", line 5, in <module>
    from ._baseline import baseline_command
  File "/home/NINA.NO/benjamin.cretois/.cache/pypoetry/virtualenvs/edna-etl-HihhyK_G-py3.10/lib/python3.10/site-packages/flakehell/commands/_baseline.py", line 6, in <module>
    from .._patched import FlakeHellApplication
  File "/home/NINA.NO/benjamin.cretois/.cache/pypoetry/virtualenvs/edna-etl-HihhyK_G-py3.10/lib/python3.10/site-packages/flakehell/_patched/__init__.py", line 2, in <module>
    from ._app import FlakeHellApplication
  File "/home/NINA.NO/benjamin.cretois/.cache/pypoetry/virtualenvs/edna-etl-HihhyK_G-py3.10/lib/python3.10/site-packages/flakehell/_patched/_app.py", line 10, in <module>
    from flake8.options.config import MergedConfigParser, get_local_plugins
ImportError: cannot import name 'MergedConfigParser' from 'flake8.options.config' (/home/NINA.NO/benjamin.cretois/.cache/pypoetry/virtualenvs/edna-etl-HihhyK_G-py3.10/lib/python3.10/site-packages/flake8/options/config.py)
```

**Comment by mlech-payability** [comment]
Looks like `flake8` 4.x is incompatible with `flakehell`. I recommend pin to the major version for the projects that use SemVer.
![image](https://user-images.githubusercontent.com/82024968/137318225-e67c0cdd-9b16-4958-b1d3-2bbab4b74426.png)

**Comment by mcarans** [comment]
I've completed the PR so that all tests pass.

**Comment by jose-rojas0** [comment]
For those looking for an alternative - take a look at https://github.com/flakeheaven/flakeheaven

**Comment by nilox94** [comment]
I had to explicitly add `flake8` as a dev dependency and pin it to version `3.9.0`.
```
[tool.poetry.dev-dependencies]
flakehell = "^0.9.0"
flake8 = "3.9.0"
```
